In [1]:
import numpy as np

## Numpy

In [2]:
# Python: List

# 1D: 1 axis
[0, 1, 2, 3]  # 4 elements, length is 4

# 2D: 2 axes
[[0, 1, 2, 3],
 [4, 5, 6, 7]]
 # The length of first axis is 2,
 # the length of second axis is 4

[[0, 1, 2, 3], [4, 5, 6, 7]]

### Create Numpy ndarray

In [3]:
# create 1 axis array from 0 to 3 (not included)
x = np.arange(3) # range()

print(x) # [0, 1, 2]
print(type(x))  # <class 'numpy.ndarray'>

# Specify a float data type
y = np.arange(5, dtype='float64')
print(y) # [0. 1. 2. 3. 4.]

[0 1 2]
<class 'numpy.ndarray'>
[0. 1. 2. 3. 4.]


### Create numpy.ndarray from Python List

In [4]:
python_list = [55, 66]

numpy_array = np.array(python_list)

print(python_list, type(python_list)) # [55, 66] <class 'list'>
print(numpy_array, type(numpy_array)) # [55 66] <class 'numpy.ndarray'>

[55, 66] <class 'list'>
[55 66] <class 'numpy.ndarray'>


### Attributes of  ndarray

In [5]:
# 1D

x = np.arange(3)
print(x) # [0, 1, 2]

# ndim - number of axes (dimensions)
print(x.ndim)  # 1 dim

# shape - dimensions of the array
print(x.shape)  # (3, )

# size - the total number of elements
print(x.size)  # 3

# dtype - the type of the elements
print(x.dtype)  # int64

[0 1 2]
1
(3,)
3
int64


In [6]:
# 2D

x = np.array([[0, 1, 2], [3, 4, 5]])
print(x)
# [[0 1 2]
#  [3 4 5]]

# ndim - number of axes (dimensions)
print(x.ndim)  # 2

# shape - dimensions of the array
print(x.shape)  # (2, 3)

# size - the total number of elements
print(x.size)  # 6

[[0 1 2]
 [3 4 5]]
2
(2, 3)
6


### Numpy Array reshape

In [7]:
# reshape
x = np.arange(6)
print(x)  # [0 1 2 3 4 5]

# Method 1
new_shape = x.reshape(3, 2)
new_shape = x.reshape(-1, 2)
print(new_shape)
# [[0 1]
#  [2 3]
#  [4 5]]

# Method 2
new_shape = np.reshape(x, (3, 2))
new_shape = np.reshape(x, (-1, 2))

# All in 1 line
y = np.arange(6).reshape(2, 3)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


### Initialize with Value

In [8]:
# np.zeros: filled with 0
np.zeros(2)  # array([ 0.,  0.])
np.zeros((2, 3))
# array([[ 0.,  0.,  0.],
#        [ 0.,  0.,  0.]])

# np.ones: filled with 1
np.ones((2, 3))
# array([[ 1.,  1.,  1.],
#        [ 1.,  1.,  1.]])

# np.full: filled with given value
np.full(shape=(4, 3), fill_value=7788)
# array([[5566, 5566, 5566],
#        [5566, 5566, 5566]])


array([[7788, 7788, 7788],
       [7788, 7788, 7788],
       [7788, 7788, 7788],
       [7788, 7788, 7788]])

### Initialize with Random Value

In [9]:
# Uniform distribution: [0, 1)
print(np.random.random(size=(3)))

# Normal distributution
# loc: mean
# scale: std
print(np.random.normal(loc=0.0, scale=1.0, size=(2, 2)))

# Random integer
print(np.random.randint(low=1, high=10, size=(3, 3)))

[0.96310991 0.11583484 0.1992905 ]
[[-2.92041866 -1.45015904]
 [-0.74144808 -0.44649465]]
[[1 8 3]
 [6 7 3]
 [3 2 5]]


### Array Index

In [10]:
# 1D array
# start: 0
# last: -1
x = np.arange(6)  # array([0, 1, 2, 3, 4, 5])
x[1]   # 1
x[-3]  # 3

# 2D array
x = np.arange(6).reshape(2, 3)  #[[0, 1, 2],
                                # [3, 4, 5]])
x[0, 1]   # 1
x[1, -2]  # 4

4

### Array Slice & Stride

In [11]:
import numpy as np

# start: end(X)
# start: end(X): stride(1)

# 1D array
x = np.arange(6)  # array([0, 1, 2, 3, 4, 5])
x[1: 5]   # [1, 2, 3, 4]
x[1: 6]   # x[1:],  [1, 2, 3, 4, 5]
x[:3]     # x[0:3] , [0, 1, 2]
x[1:4:2]  # [1, 3]

# 2D array
x = np.arange(6).reshape(2, 3)  #[[0, 1, 2],
                                # [3, 4, 5]])
x[0, 0:2]    #  [0, 1]
x[:, 1:]     # [[1, 2],
             #  [4, 5]]
x[::1, ::2]  # [[0, 2],
             #  [3, 5]]

# reverse last dimension
# e.g: BRG -> RGB
x[:, ::-1] # [[2, 1, 0],
           #  [5, 4, 3]]

array([[2, 1, 0],
       [5, 4, 3]])

### Boolean / Mask Index

In [12]:
x = np.arange(6)  # array([0, 1, 2, 3, 4, 5])

condition = x<4
x[condition] # [0, 1, 2, 3]

x[x<4] # [0, 1, 2, 3]

x[condition] = 0
x[x<4] = 0
x # [0, 0, 0, 0, 4, 5]

# Mask
# original x      # [ 0, 1, 2, 3, 4, 5]
# if <4, assign 0
print(condition)  # [ True  True  True True  False False]
x                 # [ 0,    0,    0,   0,    4,    5]

[ True  True  True  True False False]


array([0, 0, 0, 0, 4, 5])

### Concatenate (Concat)
Join a sequence of arrays along an existing axis.



In [13]:
x = np.array([[0, 1, 2], [3, 4, 5]]) # (2, 3)
y = np.array([[6, 7, 8]])            # (1, 3)

print(x.shape, y.shape)

# (2, 3) (1, 3) -> (3, 3)
np.concatenate((x, y), axis=0)  # [[0, 1, 2],
                                #  [3, 4, 5],
                                #  [6, 7, 8]]

# (2, 3) (2, 1) -> (2, 4)
z = np.array([[55], [66]])
print(z.shape)
np.concatenate((x, z), axis=1)  # [[0, 1, 2, 55],
                                #  [3, 4, 5, 66]]

(2, 3) (1, 3)
(2, 1)


array([[ 0,  1,  2, 55],
       [ 3,  4,  5, 66]])

### Basic Operations

In [14]:
import numpy as np
a = np.array([[0, 1], [2, 3]])
b = np.array([[4, 5], [6, 7]])

print(a + b)  # array([[4, 6], [8, 10]])
print(a - b)  # array([[-4, -4], [-4, -4]])
print(a * b)  # array([[0, 5], [12, 21]])
print(a / b)  # array([[0, 0.2], [0.3333, 0.42857143]]

print(a - 3)  # array([[-3, -2], [-1, 0]])
print(a * 2)  # array([[0, 2], [4, 6]])
print(a / 2)

[[ 4  6]
 [ 8 10]]
[[-4 -4]
 [-4 -4]]
[[ 0  5]
 [12 21]]
[[0.         0.2       ]
 [0.33333333 0.42857143]]
[[-3 -2]
 [-1  0]]
[[0 2]
 [4 6]]
[[0.  0.5]
 [1.  1.5]]


### Basic Statistics

In [15]:
x = np.arange(10) # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

print(np.min(x), x.min())
print(np.max(x), x.max())
print(np.mean(x), x.mean())
print(np.std(x), x.std())

0 0
9 9
4.5 4.5
2.8722813232690143 2.8722813232690143


In [16]:
# np.Argmax: get max or min index
x = np.random.normal(size=(10)) # np.arange(10)
print(np.argmax(x), np.argmin(x))
x

2 0


array([-1.71463288,  0.76642581,  1.8661824 , -0.47525857, -0.71866887,
        0.32510716, -0.03890509,  0.08331299,  0.57102981, -0.94517373])

### expand_dim & squeeze

In [17]:
import numpy as np

In [18]:
x = np.ones((128, 128))
print(x.shape) # (128, 128) : 2D

x = np.expand_dims(x, axis=0)
x2 = np.ones((128, 128))[np.newaxis, :, :]
print("np.expand_dims: ", x.shape) # (1, 128, 128) : 3D
print("np.newaxis: ", x2.shape)

x = np.expand_dims(x, axis=-1)
print(x.shape) # (1, 128, 128, 1) : 4D

x = np.squeeze(x, axis=-1)
print(x.shape) # (1, 128, 128) : 3D

(128, 128)
np.expand_dims:  (1, 128, 128)
np.newaxis:  (1, 128, 128)
(1, 128, 128, 1)
(1, 128, 128)


### np.unique

In [19]:
x = np.random.randint(low=1, high=10, size=(10))
print(x)

unique_values = np.unique(x)
print(unique_values, '\n')

unique_values, counts = np.unique(x, return_counts=True)
print(unique_values)
print(counts)

[5 8 9 8 4 1 6 1 6 5]
[1 4 5 6 8 9] 

[1 4 5 6 8 9]
[2 1 2 2 2 1]


## Reference Answers for Exercises

#### Q1 Create a 1D array with values from 10 to 19 **(Hint: np.arange)**

In [20]:
# 1
x = np.arange(10, 20)
print(x)

[10 11 12 13 14 15 16 17 18 19]


#### Q2: Reverse a verctor
ex: [0, 1, 2] -> [2, 1, 0]

In [21]:
# 2
x = np.arange(6)
x = x[::-1]
print(x)

[5 4 3 2 1 0]


#### Q3: Create a 3x3x3 array with random values
**(Hint: np.random.random or np.random.normal)**

In [22]:
# 3
x = np.random.random((3, 3, 3))
print(x)

[[[0.38811941 0.23128315 0.45609233]
  [0.15408973 0.13205727 0.14682961]
  [0.13106121 0.94575697 0.92201613]]

 [[0.44673268 0.52225314 0.52175606]
  [0.17593387 0.97291551 0.95049527]
  [0.5475192  0.85851188 0.36174456]]

 [[0.48215709 0.82490291 0.19989153]
  [0.67725607 0.31239593 0.70001134]
  [0.01633236 0.00807162 0.32841546]]]


#### Q4. Create a 5x5 array with random values and find the minimum and maximum
**(Hint: np.min, np.max)**

In [23]:
# 4
x = np.random.random((5, 5))
xmin, xmax = np.min(x), np.max(x) # or x.min(), x.max()
print(xmin, xmax)

0.11952795124597448 0.9377774265965158


#### Q5 :Add a border (filled with 0's) around an 3 * 3 matrix with width 1
**Hint: np.pad**

In [24]:
# 5
x = np.ones((3, 3))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### Q6. Normalize a 3x3 random matrix to 0~1
**(Hint: (x - x min) / (x max - x min))**

In [25]:
# 6
x = np.random.random((3, 3))
x2 = (x - np.min(x)) / (np.max(x) - np.min(x))
print(x)
print(x2)

[[0.42711202 0.73803461 0.45696399]
 [0.5739834  0.80500274 0.37774023]
 [0.7280408  0.27216993 0.01582169]]
[[0.52116093 0.91514224 0.55898745]
 [0.707267   1.         0.45860014]
 [0.90247873 0.32482818 0.        ]]


#### Q7. Given a 1D array (0 ~ 12), negate all elements which are between 2 and 9.
ex: [2, 3, 4, 10, 11] -> [-2, -3, -4, 10, 11]

In [26]:
# 7
x = np.arange(2, 12)
x[(2 < x) & (x < 9)] *= -1
print(x)

[ 2 -3 -4 -5 -6 -7 -8  9 10 11]


Q8. Extract from the array [6, 7, 8, 10, 24, 45, 99,100] by the below conditions
 1. which are not divisible by 3
 2. which are divisible by 5
 3. which are divisible by 3 and 5

In [27]:
# 8
x = np.array([6, 7, 8, 10, 24, 45, 99,100])
div3 = x[x%3 != 0]
print(div3)

div5 = x[x%5 == 0]
print(div5)

div15 = x[(x%3 == 0) & (x%5 == 0)]
print(div15)

[  7   8  10 100]
[ 10  45 100]
[45]


#### Q9. Create random vector of size 10 and replace the maximum value by 0
**Hint: np.argmax**

In [28]:
# 9
x = np.random.random(10)
x[x.argmax()] = 0
print(x)

[0.07229169 0.42494324 0.63902539 0.         0.69235396 0.66351092
 0.44350993 0.07518071 0.42065708 0.80842419]


#### Q10. Create a 3x5 matrix and the row values are from 0 to 4

In [29]:
# Broadcast
# 10
x = np.zeros((3, 5))
y = np.arange(5)
z = x + y
print(x.shape, x)
print(y.shape, y)
print(z.shape, z)

(3, 5) [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(5,) [0 1 2 3 4]
(3, 5) [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
